ALTER TABLE equipments MODIFY id INT NOT NULL COMMENT '装備ID';
ALTER TABLE bodies MODIFY id INT NOT NULL COMMENT '素体ID';
ALTER TABLE hoge_interfaces MODIFY id INT NOT NULL COMMENT 'hogeインタフェースID';
ALTER TABLE parameters MODIFY id INT NOT NULL COMMENT 'パラメータID';