ALTER TABLE equipments MODIFY id INT AUTO_INCREMENT COMMENT '装備ID';
ALTER TABLE bodies MODIFY id INT AUTO_INCREMENT COMMENT '素体ID';
ALTER TABLE hoge_interfaces MODIFY id INT AUTO_INCREMENT COMMENT 'hogeインタフェースID';
ALTER TABLE parameters MODIFY id INT AUTO_INCREMENT COMMENT 'パラメータID';